name: TestAndDeploy

on: [push]

jobs:
#  laravel-tests:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1.1.0
#    - name: Copy .env
#      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#    - name: Install Dependencies
#      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
#    - name: Generate key
#      run: php artisan key:generate
#    - name: Create Database
#      run: |
#        mkdir -p database
#        touch database/database.sqlite
#    - name: Execute tests (Unit and Feature tests) via PHPUnit
#      env:
#        DB_CONNECTION: sqlite
#        DB_DATABASE: database/database.sqlite
#      run: vendor/bin/phpunit
  laravel-deploy:
    #needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.1.0
    - name: Update Composer
      run: composer update
    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install JS Dependencies
      run: npm ci
    - name: Transpile assets
      run: npm run prod
    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRODUCTION_PRIVATE_KEY }}" >> ~/.ssh/id_dsa
        chmod 600 ~/.ssh/id_dsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        rsync -rav --delete --exclude-from '.deploy_excludes.txt' ./ ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }}:${{ secrets.PRODUCTION_PATH }}
    - name: Migrate DB on server
      run: ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan migrate:fresh --seed --force"
    - name: Optimizations
      run: |
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan clear-compiled"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan optimize"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan cache:clear"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan config:clear"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan route:clear"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan view:clear"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan config:cache"
        ssh -p22 ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd ${{ secrets.PRODUCTION_PATH }} && /opt/plesk/php/7.3/bin/php artisan route:cache"
